# coding=utf-8
"""Config module.

This module contains config classes which define common config templates for
the flask app generated by create_app() (see app.py).
To define your own config template, create a class which inherits from
the BaseConfig class.

"""


class BaseConfig(object):
    """Base config. All config classes should inherit from this."""
    TEST = False
    SQLALCHEMY_DATABASE_URI = 'sqlite:///resting.db'
    SQLALCHEMY_TRACK_MODIFICATIONS = False


class TestingConfig(BaseConfig):
    """Test config. Default config for testing."""
    TESTING = True


class DevelopmentConfig(BaseConfig):
    """Development config. Recommended config for development."""
    TESTING = True
    DEBUG = True


class ProductionConfig(BaseConfig):
    """Production config. Default config for production."""
    pass
